name:                hascade
version:             0.1.0.0
github:              "githubuser/hascade"
license:             BSD3
author:              "Yiming Fang"
maintainer:          "yf2484@columbia.edu"
copyright:           "2022 Yiming Fang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hascade#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parallel
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -eventlog

library:
  source-dirs: src

executables:
  hascade-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    - -Wall
    dependencies:
    - hascade

tests:
  hascade-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    - -Wall
    dependencies:
    - hascade
